NEGATIVE_APPRAISALS: dict[str, str] = {
    # --- original items ---
    "Self-Blame":           "The event happened because of the way I acted",
    "Self-Doubt":           "I can't trust that I will do the right thing",
    "Weakness Belief":      "I am a weak person",
    "Fear of Rage":         "I will not be able to control my anger and will do something terrible",
    "Low Coping":           "I can't deal with even the slightest upset",
    "Lost Happiness":       "I used to be a happy person but now I am always miserable.",
    "Mistrust":             "People can't be trusted",
    "Hypervigilance":       "I have to be on guard all the time",
    "Emotional Numbness":   "I feel dead inside",
    "Fear of Harm":         "You can never know who will harm you",
    "Constant Vigilance":   "I have to be especially careful because you never know what can happen next",
    "Inadequacy":           "I am inadequate",
    "Thought Avoidance":    "If I think about the event, I will not be able to handle it",
    "Character Blame":      "The event happened to me because of the sort of person I am",
    "Fear Going Crazy":     "My reactions since the event mean that I am going crazy",
    "Lost Emotions":        "I will never be able to feel normal emotions again",
    "World is Dangerous":   "The world is a dangerous place",
    "Others-Would-Cope":    "Somebody else would have stopped the event from happening",
    "Permanent Damage":     "I have permanently changed for the worse",
    "Dehumanization":       "I feel like an object, not like a person",
    "Self-Comparison":      "Somebody else would not have gotten into this situation",
    "Can't Rely on Others": "I can't rely on other people",
    "Isolation":            "I feel isolated and set apart from others",
    "Hopelessness":         "I have no future",
    "Helplessness":         "I can't stop bad things from happening to me",
    "Distrust Others":      "People are not what they seem",
    "Life Destroyed":       "My life has been destroyed by the trauma",
    "Defective Self":       "There is something wrong with me as a person",
    "Bad Coper":            "My reactions since the event show that I am a lousy coper",
    "Intrinsic Fault":      "There is something about me that made the event happen",
    "Identity Loss":        "I feel like I don't know myself anymore",
    "Can't Rely on Self":   "I can't rely on myself",
    "No Good Ahead":        "Nothing good can happen to me anymore",
    # --- new items ---
    # Shame & contamination
    "Body Shame":           "I feel ashamed of what happened to my body",
    "Contamination":        "I feel dirty or contaminated because of what happened",
    "Humiliation":          "I feel permanently humiliated by what happened",
    "Exposed to Others":    "I feel that others can see what happened to me just by looking at me",
    # Moral injury & guilt
    "Survival Guilt":       "I feel guilty for surviving when others did not",
    "Failed to Protect":    "I should have protected others and I failed",
    "Violated Values":      "I acted in ways that go against who I am",
    "Inaction Guilt":       "I will never forgive myself for not doing more to stop what happened",
    # Betrayal & injustice
    "Betrayal":             "I was betrayed by someone I trusted",
    "Injustice":            "What happened to me was deeply unfair and nothing has been done about it",
    "No Accountability":    "The people responsible have faced no consequences",
    "Institutional Failure":"The people or institutions that should have protected me let me down",
    # Loss of safety in body
    "Body Unreliable":      "I can no longer trust my own body",
    "Body as Enemy":        "My body keeps reacting as if I am still in danger even when I am safe",
    "Physical Vulnerability":"My body has been permanently damaged by what happened",
    # Loss of meaning
    "Lost Meaning":         "Nothing in my life feels meaningful anymore",
    "Shattered Beliefs":    "My beliefs about how the world works have been completely destroyed",
    "Lost Faith":           "I have lost my faith in people, life, or a higher power",
    "Life Not Worth Living":"I am not sure my life is worth living anymore",
    # Displacement & belonging
    "Belong Nowhere":       "I no longer belong anywhere",
    "Lost Community":       "I have lost my connection to my community and culture",
    "Outsider":             "I am permanently an outsider now",
    # Role & identity
    "Failed Role":          "I have failed in my most important role in life",
    "No Longer Capable":    "I am no longer capable of doing the things that defined me",
    "Unrecognisable Self":  "The person I have become is unrecognisable to me",
}

DISTRACTION_STRATEGIES: dict[str, str] = {
    # --- original items ---
    "Thought Suppression":      "I try to push them out of my mind",
    "Memory Erasure":           "I try to erase the memory of the event",
    "Emotion Control":          "I try hard to control my emotions",
    "Distraction":              "I distract myself with something else",
    "Redirection":              "I think of something else",
    "Busyness":                 "I work hard at keeping busy with other things",
    "Sexual Coping":            "I release my tension with sexual fantasies/ activities",
    "Counterfactual Thinking":  "I think about how life would have been different if the event had not occurred",
    "Prevention Rumination":    "I dwell on how the event could have been prevented",
    "Meaning Seeking":          "I think about why the event has happened to me",
    "Past Dwelling":            "I dwell on how I used to be before the event",
    "Other-Blame Rumination":   "I dwell on what other people have done to me",
    "Self-Blame Rumination":    "I dwell on what I have done wrong",
    "Downward Comparison":      "I remind myself it could have been worse",
    "Emotional Numbing":        "I numb my feelings",
    "Memory Detachment":        "I detach myself from the memories",
    "Dissociation":             "I pretend it happened to someone else",
    "Fantasy Escape":           "I drift off into a world of my own",
    "Substance Use":            "I drink alcohol, take medication or use drugs",
    "Smoking":                  "I smoke",
    "Sensory Distraction":      "I put on loud music or TV",
    # --- new items ---
    # Cognitive distraction
    "Overanalysing":            "I go over and over the details of the event trying to make sense of it",
    "Revenge Fantasies":        "I imagine getting revenge on the people responsible",
    "Reassurance Seeking":      "I keep asking others to reassure me that I am okay",
    "Positive Reframing":       "I force myself to think only positive thoughts",
    "Magical Thinking":         "I tell myself the event did not really happen or was not that bad",
    "Catastrophising Others":   "I worry obsessively about bad things happening to people I care about",
    # Behavioural distraction
    "Overworking":              "I throw myself into work or tasks to keep my mind occupied",
    "Compulsive Cleaning":      "I clean or organise things repeatedly to feel in control",
    "Compulsive Exercise":      "I push myself to exercise excessively",
    "Screen Escape":            "I spend long hours on my phone, games, or internet to avoid thinking",
    "Overeating":               "I eat more than usual to distract myself or feel better",
    "Undereating":              "I avoid eating or restrict food as a way of coping",
    "Compulsive Spending":      "I spend money impulsively to distract or comfort myself",
    "Gambling":                 "I gamble to distract myself or feel excitement",
    # Social distraction
    "Constant Socialising":     "I keep myself constantly surrounded by people so I am never alone with my thoughts",
    "Seeking Conflict":         "I pick arguments or create drama to distract myself from the trauma",
    # Self-punishment
    "Self-Harm Distraction":    "I hurt myself physically to stop thinking about the event",
    "Punishment Thinking":      "I tell myself I deserve to suffer because of what happened",
}

AVOIDANCE_STRATEGIES: dict[str, str] = {
    # --- original items ---
    "Avoid Talking":            "Talking with others about the event or its aftermath",
    "Avoid Reminders":          "Being reminded of the event by others",
    "Avoid Similar People":     "Seeing other people that were involved in the event or that look similar",
    "Avoid Social Contacts":    "Seeing people that I socialised with before the event",
    "Avoid Thinking":           "Thinking about the event",
    "Avoid Media":              "Watching TV programmes/ films or reading about similar events",
    "Avoid Location":           "Going to or near the place where the event happened",
    "Avoid Circumstances":      "Being in circumstances that remind me of the event (eg, being in the dark).",
    "Avoid Medical Cues":       "Hospitals/ Ambulances/ Physical Examinations",
    "Avoid Police":             "Police",
    "Avoid Exercise":           "Exercise",
    "Avoid Sex":                "Sex",
    "Avoid Going Out":          "Going out",
    "Avoid Physical Stress":    "Situations that put my body under stress",
    "Avoid Emotional Stress":   "Situations that make me feel strong emotions",
    "Avoid Evaluation":         "Situations in which other people evaluate me / my appearance / my performance",
    # --- new items ---
    # Interpersonal avoidance
    "Avoid Intimacy":           "Being emotionally close or intimate with others",
    "Avoid New Relationships":  "Starting new friendships or relationships",
    "Avoid Authority Figures":  "Being around people in authority or uniform",
    "Avoid Being Alone":        "Being alone in a room or building",
    "Avoid Being Touched":      "Any form of physical contact with others",
    "Avoid Eye Contact":        "Making eye contact with other people",
    "Avoid Conflict":           "Any situation that might involve disagreement or confrontation",
    # Situational avoidance
    "Avoid Night":              "Going out at night or being outside after dark",
    "Avoid Driving":            "Driving or being a passenger in a vehicle",
    "Avoid Public Transport":   "Using public transport",
    "Avoid Crowds":             "Crowded places such as shopping centres or public events",
    "Avoid Open Spaces":        "Open or exposed spaces where I feel vulnerable",
    "Avoid Enclosed Spaces":    "Enclosed or confined spaces",
    "Avoid Work or Study":      "Going to work or study",
    "Avoid Medical Care":       "Seeking medical or psychological help",
    "Avoid Religious Spaces":   "Places of worship or religious gatherings",
    # Internal avoidance
    "Avoid Own Body":           "Paying attention to or looking at my own body",
    "Avoid Feelings":           "Allowing myself to feel any strong emotion",
    "Avoid Positive Events":    "Situations that might make me feel happy or hopeful",
    "Avoid Future Plans":       "Making any plans for the future",
    "Avoid Sleep":              "Going to sleep or lying in the dark",
    "Avoid Dreams":             "Situations or times of day that tend to bring on nightmares",
    # Trauma-specific avoidance
    "Avoid Perpetrator Cues":   "Anything that reminds me of the person who harmed me",
    "Avoid News":               "News reports about events similar to what happened to me",
    "Avoid Anniversaries":      "Dates or anniversaries connected to the event",
    "Avoid Grief Reminders":    "Anything that reminds me of someone I have lost",
    "Avoid Uniform or Weapons": "Military, police uniforms or weapons",
}

TRIGGERS: dict[str, str] = {
    # --- original items ---
    "Olfactory (Alcohol)":           "Alcohol smell",
    "Olfactory Danger Cue":          "Burnt smell",
    "Auditory (Babies)":             "Babies",
    "Auditory (Cars)":               "Car sounds",
    "Auditory/Threat":               "Gunshot noise",
    "Auditory (Children Crying)":    "Kids crying",
    "Auditory (Loud Noises)":        "Loud noises",
    "Auditory/Mechanical":           "Motorcycle noise",
    "Auditory (Sirens)":             "Sirens",
    "Auditory (Language)":           "Shouting in Arabic",
    "Auditory (Language Confusion)": "Incomprehensible chatter",
    "Auditory (Voice)":              "Related voice",
    "Auditory (Sounds)":             "Related sounds",
    "Olfactory (Smell)":             "Related smells",
    "Visual (Photos)":               "Related photos",
    "Visual/Bodily Cues":            "Blood",
    "Tactile (Unexpected Touch)":    "Being touched unprepared",
    "Tactile (Touch)":               "Physical touch",
    "Cold Temperature":              "Cold",
    "Somatic Pain (Neck)":           "Neck pain",
    "Animals":                       "Dogs",
    "Emergency Contexts":            "Ambulances",
    "Transportation (Bicycle)":      "Bicycle",
    "Public Transport":              "Bus riding",
    "Crash Imagery":                 "Cars hit by accident",
    "Car Similarity":                "Similar cars",
    "Driving with Others":           "Driving with people",
    "Media Exposure":                "Related media content",
    "Media / News":                  "Related news",
    "Workplace":                     "Workplace",
    "Military Topics":               "Talks about military",
    "Animal Phobia":                 "Talks or photos about snakes",
    "Sexual Trauma Cues":            "Comments on sexual violence",
    "Violence":                      "Violence",
    "Old Memories":                  "Old photos",
    "Perceived Threat":              "People acting suspiciously",
    "Others Cycling":                "People cycling",
    "Authority Presence":            "Police",
    "Authority Figures":             "People in uniform",
    "Spatial Triggers":              "Physical locations",
    "Proximity":                     "Physical proximity",
    "Crowding":                      "Crowded places",
    "Crowding/Overstimulation":      "Crowded spaces",
    "Darkness":                      "Dark spaces",
    "Ethnic/Geographic Tension":     "Arab villages",
    "Moral Violation":               "People misbehaving",
    "Male Presence":                 "Being alone with men",
    "Sexual Objectification":        "Being looked at sexually",
    "Family-Related Comments":       "Comments on family",
    "Conflict":                      "Confrontations",
    "Shouting":                      "Shouting",
    "Arguments":                     "Arguments",
    "Stranger Interaction":          "Talking to strangers",
    "Idealized Families":            "Happy families",
    "Known People":                  "Related people",
    "Event Involvement":             "People who are related to the event",
    "Victim Similarity":             "People who look similar to the victims",
    "Relationship Reminders":        "When people say things like my ex",
    "Offender Cues":                 "Seeing the offender",
    "Event Recall":                  "Talking about the event",
    "Crash Discussions":             "Talk about accidents",
    "Loss Themes":                   "Talk about people loosing loved ones",
    "Name Reminders":                "Hearing related names",
    "Victim Memories":               "Reminders of victims",
    "Trauma-Related Events":         "Trauma-related events",
    "Certain Songs":                 "Certain songs",
    "Certain Conversation Topics":   "Certain conversation topics",
    "Loss of Autonomy":              "Being forced to do something",
    "Vulnerability":                 "Being naked",
    "Self-Consciousness":            "Being seen",
    "Entrapment":                    "Having no options",
    "Loss of Control":               "Lack of control",
    "Discomfort":                    "Feeling uncomfortable",
    "Positive Emotion Confusion":    "Positive emotions",
    "Future Orientation":            "Talking about the future",
    "Uncertainty":                   "Uncertainty",
    "Unpredictability":              "Unpredictable situations",
    "Intrusive Thoughts":            "Unwanted thoughts",
    "Stress":                        "Stress",
    "Affective Expression":          "Crying",
    "Object Throwing":               "Throwing objects",
    # --- new items ---
    # Sensory — new
    "Olfactory (Sweat/Body)":        "Sweat or body odour",
    "Olfactory (Hospital)":          "Hospital or antiseptic smell",
    "Olfactory (Smoke)":             "Smoke or fire smell",
    "Olfactory (Cologne/Perfume)":   "A specific perfume or cologne",
    "Olfactory (Earth/Outdoor)":     "Soil or outdoor smells",
    "Auditory (Helicopter)":         "Helicopter or aircraft sounds",
    "Auditory (Explosion)":          "Explosion or bang sounds",
    "Auditory (Silence)":            "Sudden or complete silence",
    "Auditory (Breathing)":          "Heavy breathing sounds",
    "Auditory (Footsteps)":          "Footsteps behind or nearby",
    "Auditory (Door)":               "Doors opening or slamming",
    "Visual (Uniforms)":             "Military or police uniforms",
    "Visual (Weapons)":              "Weapons or objects used as weapons",
    "Visual (Injuries)":             "Visible injuries or wounds on others",
    "Visual (Needles/Medical)":      "Medical equipment such as needles or drips",
    "Visual (Fire/Flames)":          "Fire or flames",
    "Visual (Water/Flooding)":       "Water, flooding, or large bodies of water",
    "Visual (Body Parts)":           "Specific body parts associated with the event",
    "Gustatory (Taste)":             "A specific taste associated with the event",
    "Tactile (Restrained)":          "Feeling physically restrained or held down",
    "Tactile (Temperature)":         "A specific temperature on the skin",
    "Tactile (Texture)":             "A specific texture associated with the event",
    "Somatic (Heart Racing)":        "Own heart racing or pounding",
    "Somatic (Dizziness)":           "Feeling dizzy or lightheaded",
    "Somatic (Breathlessness)":      "Difficulty breathing or feeling short of breath",
    "Somatic (Nausea)":              "Feeling nauseous",
    "Somatic (Pain)":                "Physical pain in a part of the body",
    # Situational — new
    "Nighttime/Dark":                "Night-time or waking up in the dark",
    "Sleeping Alone":                "Sleeping alone or in an unfamiliar place",
    "Being Watched":                 "Feeling watched or observed",
    "Being Followed":                "Feeling followed or tracked",
    "Locked Spaces":                 "Being in a locked or confined room",
    "Medical Procedures":            "Undergoing a medical examination or procedure",
    "Sexual Situations":             "Sexual situations or intimacy",
    "Pregnancy/Birth Reminders":     "Pregnancy, childbirth, or babies in general",
    "Funerals/Graves":               "Funerals, cemeteries, or grief-related events",
    "Anniversaries":                 "The anniversary of the event",
    "Weather Similarity":            "Similar weather conditions to when the event happened",
    "Time of Day":                   "The same time of day the event occurred",
    "Being in Nature":               "Being in a natural environment similar to where it happened",
    # Interpersonal — new
    "Emotional Closeness":           "Someone getting emotionally close to me",
    "Being Praised":                 "Receiving praise or positive attention",
    "Being Criticised":              "Being criticised or corrected",
    "Expressions of Anger":          "Other people expressing anger, even calmly",
    "Expressions of Affection":      "Physical affection such as hugs",
    "Female Presence":               "Being alone with women",
    "Children Present":              "Being around children",
    "Authority Commands":            "Being given orders or instructions",
    "Power Imbalance":               "Being in a situation where someone has power over me",
    # Internal/cognitive — new
    "Feeling Happy":                 "Feeling happy or relaxed",
    "Feeling Tired":                 "Feeling very tired or exhausted",
    "Feeling Ill":                   "Feeling physically unwell",
    "Feeling Vulnerable":            "Feeling emotionally vulnerable",
    "Intrusive Memory":              "A memory of the event coming to mind suddenly",
    "Dream Residue":                 "Waking up from a nightmare",
    "Dissociative Feeling":          "Beginning to feel detached or unreal",
}


THREAT: dict[str, str] = {
    # --- original items ---
    "Flashbacks":          "Suddenly feeling or acting as if the stressful experience were actually happening again",
    "Physical Reactivity": "Having strong physical reactions when something reminded you of the stressful experience",
    "Negative Emotions":   "Having strong negative feelings such as fear, horror, anger, guilt, or shame",
    "Irritability":        "Irritable behavior, angry outbursts, or acting aggressively",
    "Risky Behavior":      "Taking too many risks or doing things that could cause you harm",
    "Hypervigilance":      "Being superalert or watchful or on guard",
    "Startle Response":    "Feeling jumpy or easily startled",
    "Concentration":       "Having difficulty concentrating",
    "Sleep Problems":      "Trouble falling or staying asleep",

    # Additional items
    "Scanning Exits":            "I scan for exits as soon as I enter any room or building",
    "Scanning for Danger":       "I constantly scan my surroundings for signs of danger",
    "Checking Behind":           "I frequently look behind me to check if someone is following me",
    "Watching Others":           "I watch other people closely for signs that they might harm me",
    "Threat in Faces":           "I study people's faces and body language to detect if they are a threat",
    "Safe Seat Seeking":         "I always choose where to sit based on how safe or protected I feel",
    "Back to Wall":              "I feel unsafe unless my back is against a wall where I can see the room",
    "Noticing Weapons":          "I notice potential weapons or dangerous objects in any environment",
    "Threat in Sounds":          "I am on high alert when I hear unexpected or loud sounds",
    "Threat in Movements":       "Sudden movements by others put me immediately on guard",
    "Body on Alert":             "My body feels constantly tense and ready to react to danger",
    "Cannot Relax":              "I am unable to relax even when I know I am in a safe place",
    "Alert at Home":             "I feel on guard even inside my own home",
    "Night Vigilance":           "I find it harder to feel safe at night than during the day",
    "Sleep Vigilance":           "I have difficulty falling asleep because I need to stay alert",
    "Waking Alert":              "I wake during the night to check whether I am safe",
    "Door and Lock Checking":    "I repeatedly check that doors and windows are locked",
    "Intrusion Monitoring":      "I listen for sounds that might mean someone is entering my home",
    "Safe Zone Only":            "I only feel safe in a very limited number of places",
    "Escape Route Planning":     "I always identify escape routes before I feel comfortable anywhere",
    "Avoid Unfamiliar Places":   "I avoid going to unfamiliar places because I cannot assess the danger",
    "Startle to Sounds":         "I jump or startle at ordinary sounds that would not bother most people",
    "Startle to Touch":          "I react with alarm when someone touches me unexpectedly",
    "Startle to Movement":       "Unexpected movement nearby causes me to react as if I am in danger",
    "Body Reacts Before Mind":   "My body reacts to danger before I have even had time to think",
    "False Alarms":              "I often react as if I am in danger even when nothing is actually wrong",
    "Cannot Trust Safety":       "Even when others tell me I am safe I find it impossible to believe it",
    "Threat from Strangers":     "I feel threatened by strangers approaching me even in ordinary situations",
    "Threat in Delays":          "When something takes longer than expected I assume something bad is happening",
    "Threat in Silence":         "Unusual silence makes me feel something dangerous is about to happen",
}


MEMORY: dict[str, str] = {
    # --- original items ---
    "Visual Memories":      "My memories of the frightening event are mostly pictures or images.",
    "Nonverbal Memory":     "I can't seem to put the frightening event into words.",
    "Auditory Recall":      "When I have memories of what happened I sometimes hear things in my head that I heard during the frightening event.",
    "Reliving Event":       "When I remember the frightening event I feel like it is happening right now.",
    "Olfactory Recall":     "When I think about the frightening event I can sometimes smell things that I smelt when the frightening event happened.",
    "Verbal Access":        "I can talk about what happened very easily.",
    "Snapshot Memory":      "I remember the frightening event as a few moments, and each moment is a picture in my mind.",
    "Memory Replay":        "My memories of the frightening event are like a film that plays over and over.",
    "Vivid Memory":         "My memories of the frightening event are very clear and detailed.",
    "Photographic Recall":  "Remembering what happened during the frightening event is just like looking at photographs of it in my mind.",
    "Bodily Reenactment":   "When memories come to mind of what happened, I feel my body is in the same position as when the frightening event occurred.",
    # --- new items ---
    # Vividness
    "More Real Than Normal":     "My memories of the event feel more real and vivid than memories of ordinary things",
    "Full Sensory Reliving":     "When the memory comes back it feels completely real across all my senses at once",
    "Pain Recall":               "When the memory returns I feel physical pain in the same parts of my body as during the event",
    "Taste Vividness":           "I can taste what I tasted during the event when the memory returns",
    "Feels Present Not Past":    "The memory feels like it is happening right now rather than something that is over",
    # Fragmentation
    "Fragmented Pieces":         "My memories of the event come in disconnected pieces that do not fit together",
    "Memory Gaps":               "There are parts of the event that I simply cannot remember no matter how hard I try",
    "Confused Sequence":         "I cannot put the memories of the event in the right order",
    "Partial Clarity":           "Some moments of the event are extremely clear while others are completely blank",
    "Incomplete Picture":        "I feel like I am only remembering parts of what happened and the rest is missing",
    "Sudden Pieces":             "Fragments of the memory appear suddenly without warning and then disappear",
    # Incoherence
    "No Coherent Story":         "I cannot tell a clear story of what happened even to myself",
    "Cannot Find Words":         "I know what happened but I am unable to find words to describe it",
    "Story Feels Unreal":        "The memory is so extreme it is hard to believe it actually happened to me",
    "Cannot Explain Clearly":    "When I try to explain what happened I lose the thread and cannot finish",
    "Memory Feels Alien":        "The memory feels like it belongs to someone else rather than to me",
    # Emotional intensity
    "Overwhelm on Recall":       "When the memory returns I feel so overwhelmed by emotion that I have to stop",
    "Terror on Recall":          "Remembering the event brings back the same terror I felt at the time",
    "Shame on Recall":           "When I remember the event I feel intense shame",
    "Guilt on Recall":           "When I remember the event I feel intense guilt",
    "Rage on Recall":            "When I remember the event I feel intense rage",
    "Grief on Recall":           "When I remember the event I feel overwhelming grief",
    "Emotion Without Image":     "Sometimes I feel the full emotional intensity of the event without any clear image or memory",
    "Emotionless Recall":        "Sometimes I can recall what happened but feel completely numb, as if it happened to a stranger",
    # Involuntary access
    "Uncontrolled Access":       "The memory forces its way into my mind when I do not want it to",
    "Triggered Without Warning": "Something in my surroundings can instantly bring back the full memory without warning",
    "Hard to Recall Deliberately":"When I try to deliberately remember what happened I find it difficult to access the memory",
    "Blocked Before Complete":   "I find myself pushing the memory away before I can fully recall it",
}


MALADAPTIVE_STRATEGIES: dict[str, str] = {
    # --- original items ---
    "Suppress Thoughts":             "try hard not think about the trauma",
    "Mental Distraction":            "keep mind occupied all the time",
    "Alcohol Use":                   "drink alcohol",
    "Drug Use":                      "take drugs",
    "Avoid All Feelings":            "avoid anything that could cause negative or positive feelings",
    "Rumination: Prevention":        "ruminate about how event could have been prevented",
    "Rumination: Revenge":           "ruminate about how to get even with assailant",
    "Avoid Event Site":              "avoid site of the event",
    "Avoid Similar Clothes":         "avoid wearing similar clothes",
    "Carry Weapon":                  "carry weapon",
    "Hypervigilance towards people": "vigilant for dangerous people",
    "Stay Near Exit":                "make sure to stay close to exit",
    "Mirror Checking":               "keep checking mirrors",
    "Avoid Friends":                 "avoid seeing friends",
    "Stop Enjoyment":                "give up pleasant activities",
    "Avoid People":                  "avoid other people",
    "Face Hiding":                   "cover face with hands",
    "Heavy Makeup":                  "heavy make-up",
    "Delay Sleep":                   "stay up until very late",
    "Avoid Stressors":               "avoid anything that could be stressful",
    # --- new items ---
    # Safety behaviours — body & appearance
    "Concealing Clothing":           "wear concealing clothing to avoid being noticed",
    "Body Monitoring":               "constantly check body for signs of danger or injury",
    "Checking Locks":                "repeatedly check locks, doors, or windows",
    "Checking Surroundings":         "constantly scan environment for signs of threat",
    "Escape Route Planning":         "always plan an escape route before entering a place",
    "Sit With Back to Wall":         "always sit with back against a wall to see the room",
    # Safety behaviours — interpersonal
    "Never Alone":                   "make sure never to be alone with another person",
    "Rehearse Conversations":        "rehearse what to say before any interaction",
    "Avoid Assertiveness":           "never disagree or assert myself to avoid conflict",
    "People Pleasing":               "go along with whatever others want to feel safe",
    # Cognitive safety behaviours
    "Thought Monitoring":            "constantly monitor own thoughts for signs of going crazy",
    "Suppress Anger":                "never allow myself to feel or express anger",
    "Rumination: Meaning":           "go over and over why the event happened to me",
    "Rumination: Self-Blame":        "repeatedly blame myself for what happened",
    "Worst Case Rehearsal":          "mentally rehearse worst case scenarios to feel prepared",
    "Magical Prevention":            "perform mental rituals to prevent bad things from happening again",
    # Bodily safety behaviours
    "Freeze When Threatened":        "freeze completely when feeling threatened",
    "Fawn Response":                 "become overly compliant when feeling threatened",
    "Dissociate Deliberately":       "deliberately try to leave my body or blank out",
    "Self-Harm":                     "hurt myself physically to release overwhelming feelings",
    "Restrict Eating":               "control eating strictly to feel in control",
    "Overeat":                       "eat excessively to manage distress",
    # Avoidance of internal states
    "Avoid Relaxation":              "avoid relaxing because it feels dangerous",
    "Avoid Positive Feelings":       "push away positive emotions because they feel unsafe",
    "Avoid Therapy Content":         "avoid thinking about anything discussed in therapy",
    # Occupational & social functioning
    "Overwork":                      "work excessively to avoid being alone with thoughts",
    "Isolate Completely":            "cut off all contact with friends and family",
    "Drop Responsibilities":         "give up important responsibilities to stay safe or avoid triggers",
}
